### ISSUE TITLE
Unlimited counted reactions & disappeared chosen reaction after refresh

### ISSUE THREAD

**Issue by manurohr** [ReFlar/reactions#1]
### Unlimited counted reactions & disappeared chosen reaction after refresh

Flarum 0.1.0-beta.7 PHP 7.1.16-1+ubuntu16.04.1+deb.sury.org+1, Nginx
Reactions: 0.1.0-beta.5.1
Browsers: Chrome v65, FF v59, Safari v11.1
OS: macOS Sierra, 10.12.6

Logs: no logs concerned to reactions in php, flarum and nginx logs. I have turned on the debug mode.

I have installed the extension using composer. It worked a while well until I have changed reactions by removing all default displayed icons/emojis in the admin and adding new icons. 
If I hover somewhere in a post, I see the smiley icon appearing. Once I hover this smiley, I see a selection of desired reactions. I click one of those reactions and I see the chosen reaction appearing next to smiley. This smiley is still present even I have chosen a reaction. This means I can click again on the same reaction directly or on tooltip as well and the reactions are just added every time I click.

After I refresh, all multiple counted icons are disappeared. 

I guess, this bug happens once I have removed icons and added new icons in the admin. The older posts contained also reactions I removed in the admin.

Here the screenshot of bug:
<img width="1142" alt="counted_icons" src="https://user-images.githubusercontent.com/38522534/38982754-fe9fb566-43c2-11e8-9542-aef54340d1dd.png">

**Comment by Ralkage** [comment]
Please post the output of "php flarum info" from running this in the root directory of your Flarum installation. You can use SSH or whatever means, but we need to know what other extensions you have to be able to try and reproduce your issue.

**Comment by manurohr** [comment]
```
Flarum core 0.1.0-beta.7
PHP 7.1.16-1+ubuntu16.04.1+deb.sury.org+1
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache
EXT flarum-akismet v0.1.0-beta.6
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT wiwatsrt-best-answer v0.1.0-beta.11
EXT datitisev-dashboard v0.1.0-beta.6.1
EXT cbmainz-de 0.7.1
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.7
EXT flagrow-bazaar 0.2.4
EXT flagrow-byobu 0.1.2
EXT flagrow-impersonate 0.1.0
EXT flagrow-split 0.2
EXT flagrow-upload 0.6.0
EXT flagrow-user-directory 0.1.0
EXT flagrow-users-list 0.1.2
EXT flarum-flags v0.1.0-beta.7
EXT sijad-recaptcha 0.0.2
EXT flarum-likes v0.1.0-beta.6
EXT sijad-links 0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT xengine-markdown-editor 1.3.1
EXT flarum-mentions v0.1.0-beta.7
EXT sijad-pages 0.1.0-beta.3
EXT reflar-polls 0.1.1
EXT reflar-reactions 0.1.0-beta.5.1
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
Base URL: http://165.227.155.233
Installation path: /var/www/html
```

**Comment by CDK2020** [comment]
I believe I have found the problem. It looks like when there isn't a reaction with an id of "1" it breaks down, still trying to find a fix
