### ISSUE TITLE
reaction not correctly saved after other user has reacted

### ISSUE THREAD

**Issue by manurohr** [ReFlar/reactions#3]
### Reaction not correctly saved after other user has reacted

I have re-installed reactions due to a bug [here](https://github.com/ReFlar/reactions/issues/1). The unlimited counted reactions seems to be fixed so I have tested it on my local environment again. I set up two different users (one is admin and other one is normal user belonging to a certain group).
One user is signed in in a safari browser while other admin user is signed in in the chrome browser.

The admin reacts on the initial post. It shows one counted emoji which is fine. The smiley with plus (for choosing reactions by hovering) is not visible anymore which is also ok.

I switch to other user in safari and I refresh the page where the initial post is. I see a counted emoji reacted by admin before which is also fine. I choose the same reaction by hovering the smiley with plus. Now I see a counted emoji with a number of two. I also do not see smiley with plus anymore. It works as expected.

When I switch again back to admin and refresh the page, I see the counted emoji with a number two and **also smiley with plus** . Even as admin I have reacted already on the same post, this smiley with plus appears again and I can choose any reaction again. After I do refresh, all counted emojis disappeared. As normal user in other browser I also do not see any reactions anymore too.

I expect not to see anymore the selection of emojis after I and other users have reacted. 

<img width="932" alt="reactions_smiley_visible_after_other_user_has_reacted" src="https://user-images.githubusercontent.com/38522534/39188982-64d8a222-47d1-11e8-8bc8-ffb05fe11bac.png">

## Technical Details

Flarum 0.1.0-beta.7 PHP 7.1.12, Nginx
Reactions: 1.0.0-beta.1
Browsers: Chrome v66, FF v59, Safari v11.1
OS: macOS Sierra, 10.12.6

Logs: no logs concerned to reactions in php, flarum and nginx logs. I have turned on the debug mode.

I also tried `php flarum cache:clear`.

## Flarum Info

```
Flarum core 0.1.0-beta.7
PHP 7.1.12
Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, SPL, iconv, intl, json, ldap, mbstring, session, standard, mysqlnd, PDO, pdo_mysql, pdo_sqlite, apcu, posix, readline, Reflection, mysqli, SimpleXML, soap, sockets, exif, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, apc, Phar, imap, mcrypt, gettext, pgsql, pdo_pgsql
EXT flarum-akismet v0.1.0-beta.6
EXT flagrow-analytics 0.6.0
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT wiwatsrt-best-answer v0.1.0-beta.11
EXT datitisev-dashboard v0.1.0-beta.6.1
EXT cbmainz-de 0.7.1
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.7
EXT flagrow-bazaar 0.2.4
EXT flagrow-byobu 0.1.2
EXT flagrow-impersonate 0.1.0
EXT flagrow-split 0.2
EXT flagrow-upload 0.6.0
EXT flagrow-user-directory 0.1.0
EXT flagrow-users-list 0.1.2
EXT flarum-flags v0.1.0-beta.7
EXT sijad-google-analytics 0.1.1
EXT sijad-recaptcha 0.0.2
EXT davis-inviteonly v0.1.0-beta4
EXT flarum-likes v0.1.0-beta.6
EXT sijad-links 0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT xengine-markdown-editor 1.3.1
EXT flarum-mentions v0.1.0-beta.7
EXT sijad-pages 0.1.0-beta.3
EXT reflar-polls 0.1.1
EXT reflar-reactions 1.0.0-beta.1
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
Base URL: http://localhost:7888/quickline
Installation path: /Applications/MAMP/htdocs/quickline
```

**Comment by CDK2020** [comment]
Thank you for the very detailed report, much appreciated! 

I have been able to reproduce the issue on my end, expect a fix soon.
