### ISSUE TITLE
Button-label rule impacting all buttons

### ISSUE THREAD

**Issue by spaeps** [ReFlar/reactions#6]
https://github.com/ReFlar/reactions/blob/eb6ab9f894db04a402209fd036f136bf1de2666b/less/CommentPost-ReactAction.less#L64
I do not get the purpose of this rule.

Also it decentralize the content of every button, as the "Start a discussion" one, worst it trims the text for some translations.

I disabled it by overwriting in a custom css with another !important rule and it works.
I can't see any degrade in the reaction extension visualization and I think it could be just erased.

**Comment by datitisev** [comment]
Sorry about that, my bad.
Should have only applied it to elements inside `div.Reactions`, which is what   I just changed it to. It should be fixed now.
